### PR TITLE
compare leafrefs by value

### LINKED ISSUE #7: Crash on valid config due to leafref treated as identityref
# Problem

a config containing the following leafref node `<interface-name>vprn-xyz/abcdef:accessP2P</interface-name>`

causes

```
  File "[..]/python3.6/site-packages/ncdiff/netconf.py", line 862, in node_sub
    self.node_sub(child_self, child_other)
  File "[..]/python3.6/site-packages/ncdiff/netconf.py", line 867, in node_sub
    if self._node_le(child_self, child_other) and \
  File "[..]/python3.6/site-packages/ncdiff/calculator.py", line 558, in _node_le
    if not self._node_le(child, child_other):
  File "[..]/python3.6/site-packages/ncdiff/calculator.py", line 558, in _node_le
    if not self._node_le(child, child_other):
  File "[..]/python3.6/site-packages/ncdiff/calculator.py", line 558, in _node_le
    if not self._node_le(child, child_other):
  File "[..]/python3.6/site-packages/ncdiff/calculator.py", line 519, in _node_le
    if not self._same_text(node_self, node_other):
  File "[..]/python3.6/site-packages/ncdiff/calculator.py", line 424, in _same_text
    return self._parse_text(node1) == self._parse_text(node2)
  File "[..]/python3.6/site-packages/ncdiff/calculator.py", line 390, in _parse_text
    return idref.default
  File "[..]/python3.6/site-packages/ncdiff/ref.py", line 53, in default
    return self.convert(self.node.text, to_node=None)
  File "[..]/python3.6/site-packages/ncdiff/ref.py", line 111, in convert
    url, id = self.parse_prefixed_id(tag, self.node)
  File "[..]/python3.6/site-packages/ncdiff/ref.py", line 72, in parse_prefixed_id
    .format(match.group(1), node.tag))
ncdiff.errors.ConfigError: unknown prefix 'vprn-xyz/abcdef' in the node with tag {urn:nokia.com:sros:ns:yang:sr:conf}interface-name

```

# Analysis

When building the type structure, leafref is represented as `->`  (https://github.com/CiscoTestAutomation/ncdiff/blob/master/src/ncdiff/plugins/cxml.py#L356)

When calling `_parse_text` `->` is handled as an identityref (https://github.com/CiscoTestAutomation/ncdiff/blob/master/src/ncdiff/calculator.py#L388)

### PR DESCRIPTION
**Pull request by wouterdb**
fixes #7

### CODE REVIEW

**Comment by yuekyang** [comment]
The case of leafref is a bit tricky. Some work is TBD.

**Comment by wouterdb** [comment]
Thank you for merging it!

**Comment by yuekyang** [comment]
Thank you!Jonathan
    On Friday, July 3, 2020, 02:20:48 p.m. EDT, Wouter De Borger <notifications@github.com> wrote:  
 
 


Thank you for merging it!

**Comment by wouterdb** [comment]
When could we expect another release? We would like to take these changes to production?

**Comment by yuekyang** [comment]
Hi Wouter,
We are preparing a release now. Sorry for the delay.
Thanks,Jonathan

    On Friday, November 6, 2020, 08:38:06 a.m. EST, Wouter De Borger <notifications@github.com> wrote:  
 
 


When could we expect another release? We would like to take these changes to production?

**Pull request merged**
